version: '3.3'
services:
    transmission-openvpn:
        container_name: transmission
        dns:
            - 9.9.9.9
            - 8.8.8.8
        networks: 
            - plexnet
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        volumes:
            - '${MOUNT_POINT}/transmission:/data'
        environment:
            - OPENVPN_PROVIDER=${VPN_PROVIDER}
            - OPENVPN_CONFIG=${VPN_COUNTRY}
            - OPENVPN_USERNAME=${VPN_USER}
            - OPENVPN_PASSWORD=${VPN_PASSWORD}
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=192.168.0.0/16
        logging:
            driver: json-file
            options:
                max-size: 80m
        ports:
            # transmission
            - 9091:9091
              # radarr
            - 7878:7878
              # sonarr
            - 8989:8989
              # jackett
            - "9117:9117"
        image: haugene/transmission-openvpn
    plex:
        container_name: plex
        networks: 
            - plexnet
        image: plexinc/pms-docker
        restart: unless-stopped
        ports:
          - 32400:32400/tcp
          - 3005:3005/tcp
          - 8324:8324/tcp
          - 32469:32469/tcp
          - 1900:1900/udp
          - 32410:32410/udp
          - 32412:32412/udp
          - 32413:32413/udp
          - 32414:32414/udp
        environment:
          - TZ=GB
          - PLEX_CLAIM=${PLEX_CLAIM}
          - ADVERTISE_IP=${PLEX_IP}
        hostname: ${PLEX_HOSTNAME}
        volumes:
          - plexconfig:/config # See: https://github.com/plexinc/pms-docker#windows-not-recommended
          - ${MOUNT_POINT}:/transcode
          - ${MOUNT_POINT}/media:/data
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        depends_on: 
            - transmission-openvpn
        network_mode: "service:transmission-openvpn"
        restart: unless-stopped
        environment:
          - PGID=1001
          - PUID=1001
          - TZ=Europe/London
        volumes:
          - ${MOUNT_POINT}/jackett/config:/config
          - ${MOUNT_POINT}/jackett/downloads:/downloads
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        depends_on: 
            - transmission-openvpn
        network_mode: "service:transmission-openvpn"
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - ${MOUNT_POINT}/media/TV:/tv
          - ${MOUNT_POINT}/sonarr/config:/config
          - ${MOUNT_POINT}/sonarr/recyclebin:/recyclebin
          - ${MOUNT_POINT}/transmission:/data
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        depends_on: 
            - transmission-openvpn
        network_mode: "service:transmission-openvpn"
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - ${MOUNT_POINT}/media/Movies:/movies
          - ${MOUNT_POINT}/radarr/config:/config
          - ${MOUNT_POINT}/radarr/recyclebin:/recyclebin
          - ${MOUNT_POINT}/transmission:/data
        restart: unless-stopped
    bazarr:
        image: linuxserver/bazarr
        container_name: bazarr
        networks: 
            - plexnet
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - ${MOUNT_POINT}/media/Movies:/movies
          - ${MOUNT_POINT}/media/TV:/tv
          - ${MOUNT_POINT}/bazarr:/config
        ports:
          - 6767:6767
        restart: unless-stopped
volumes: 
  plexconfig:
networks: 
    plexnet:
        driver: bridge